config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get    'about'   => 'static_pages#about'
  get    'help'    => 'static_pages#help'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div  data-alert class="alert-box <%= message_type %>">
    <strong><%= message %></strong>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">

  <div class="row">
    <div class="large-9 columns">
    <hr>
      <small>
        <p class="copyright">&copy; 2015 AppFramework, Inc. All rights reserved.</p>
      </small>
    </div>
    <div class="large-3 columns">
    <hr>
      <dl class="sub-nav">
        <dd class=""><%= link_to "About", about_path %></dd>
        <dd><%= link_to "Contact", contact_path %></dd>
      </dl>
    </div>
  </div>
  
</footer>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "AppFramework-Rails", root_path %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">

    <!-- BEGIN: Right Nav Section -->

    <ul class="right">
      <li class=""><%= link_to "Help", help_path %></li>
      <% if logged_in? %>
        <li class="has-dropdown">
          <a href="#"><%= current_user.email %></a>
          <ul class="dropdown">
            <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings",  edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
          </ul>
        </li>
        <% else %>
          <li class=""><%= link_to "Login", login_path %></li>
        <% end %>
    </ul>

    <!-- END: Right Nav Section -->

    <!-- BEGIN: Left Nav Section -->

    <ul class="left">
      <% if logged_in? %>
        <% if current_user.admin? %>
          <li><%= link_to "Users", users_path %></li>
        <% end %>
      <% end %>
    </ul>

    <!-- END: Left Nav Section -->

	</section>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="hide-for-small">
	<div class="sidebar">
		<nav>
		  <ul class="side-nav">
		    <li class="heading">Setup</li>
		    <li><a href="../index.html" data-search="">Getting Started</a></li>
		    <li><a href="../css.html" data-search="Styles">CSS</a></li>
		  </ul>
	  </nav>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>

  <!-- Header -->
  <%= render 'layouts/header' %>

    <% if logged_in? %>
      <div class="row fullWidthLogin">
        <!-- Side Nav Section -->
     		<div class="large-3 medium-4 columns">
     			<%= render 'layouts/sidebar' %>
       	</div>
        <!-- Content (logged_in) -->
        <div class="large-9 columns">
    <% else %>
      <div class="row fullWidth">
        <!-- Content (not logged_in) -->
        <div class="large-12 columns">
    <% end %>
      <!-- Content -->
          <%= render 'layouts/flash_messages' %>
        	<%= yield %>
        	<%= render 'layouts/footer' %>
        	<%= debug(params) if Rails.env.development? %>
    		</div>
        
      </div>

  </body>
</html>